name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Wähle die passende Python-Version

      - name: Install Buildozer
        run: |
          pip install --upgrade buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyKivyMD # Benenne den Artefakt-Namen
          path: ./bin # Der Pfad, in dem Buildozer die APK speichert
