name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git
          python -m pip install --upgrade pip
          pip install cython kivy buildozer

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer init
          # Edit buildozer.spec if needed
          buildozer -v android debug
