name: Android Build

on:
  push:
    branches:
      - main # oder der Name deines Hauptbranches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Versionsnummer von Python

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install distutils

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libncurses5 \
            libstdc++6 \
            zlib1g-dev \
            openjdk-8-jdk \
            unzip \
            python3-pip
          pip3 install --upgrade cython virtualenv

      - name: Install Buildozer
        run: pip3 install --user buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: my_app_debug
          path: ./bin/*.apk # Pfade entsprechend deiner APK-Generierung anpassen
